##auth/login

### POST /api/auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{"username": "hash", "password": "salasana"}

### GET my user info
GET http://127.0.0.1:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Imhhc2giLCJlbWFpbCI6Imhhc2hAcGxpaXMuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxNDE1MTQ3fQ.m7bSEtAfHs5ipiDBxLgvYoX-8vQIxX_Pb2DFnjDyJkc

### GET /users
GET http://127.0.0.1:3000/api/user

### GET /users/:id
GET http://127.0.0.1:3000/api/user/4

### POST /user
POST http://127.0.0.1:3000/api/user
content-type: application/json

  {
    "user_id": "7",
    "username": "hash",
    "password": "salasana",
    "email": "hash@pliis.com",
    "user_level_id": 1
  }

### POST /user error
POST http://127.0.0.1:3000/api/user

{"höpö": "höpö"}

### PUT /users/:id
PUT http://127.0.0.1:3000/api/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Imhhc2giLCJlbWFpbCI6Imhhc2hAcGxpaXMuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxNDE1MTQ3fQ.m7bSEtAfHs5ipiDBxLgvYoX-8vQIxX_Pb2DFnjDyJkc
content-type: application/json

  {
    "username": "tetteis",
    "password": "krgbhs",
    "email": "menu@se.fi",
    "user_level_id": 3
  }

### DELETE /users/:id
DELETE http://127.0.0.1:3000/api/user/6

#############################################

### GET /menus
GET http://127.0.0.1:3000/api/menu

### GET /menus/:id
GET http://127.0.0.1:3000/api/menu/1

### POST /menus
POST http://127.0.0.1:3000/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Imhhc2giLCJlbWFpbCI6Imhhc2hAcGxpaXMuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxNDE1MTQ3fQ.m7bSEtAfHs5ipiDBxLgvYoX-8vQIxX_Pb2DFnjDyJkc

{
  "name": "Kesämenu",
  "description": "Kesämenu 2021",
  "diet": "gluteeniton"
}

### PUT /menus/:id
PUT http://127.0.0.1:3000/api/menu/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Imhhc2giLCJlbWFpbCI6Imhhc2hAcGxpaXMuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxNDE1MTQ3fQ.m7bSEtAfHs5ipiDBxLgvYoX-8vQIxX_Pb2DFnjDyJkc

{
  "name": "Kesämenuuuuuuuuuuuu",
  "description": "Kesämenu 303030303",
  "diet": "vege"
}

### DELETE /menus/:id
DELETE http://127.0.0.1:3000/api/menu/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Imhhc2giLCJlbWFpbCI6Imhhc2hAcGxpaXMuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxNDE1MTQ3fQ.m7bSEtAfHs5ipiDBxLgvYoX-8vQIxX_Pb2DFnjDyJkc
